'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');const fail=m=>{throw new Error(m)};const git=(...a)=>cp.execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim();const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const status=git('status','--porcelain');const exposed=JSON.parse(fs.readFileSync(path.join(root,'elm.json'),'utf8'))['exposed-modules'];if(exposed.length!==7)fail('public API drift');
const packageJson=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));if(packageJson.scripts.test!=='node scripts/canonical-test.cjs')fail('canonical npm test path drift');const artifactHashes={};for(const mode of ['debug','optimize']){const p=path.join(root,'build',`runtime-${mode}.js`);if(!fs.existsSync(p))fail(`missing ${mode}`);const s=fs.readFileSync(p,'utf8');if(/@fixture|FixtureObserver|process\.exit\s*\(/.test(s))fail(`artifact leak ${mode}`);artifactHashes[mode]=sha(p);console.log(`${mode} ${fs.statSync(p).size} ${artifactHashes[mode]}`);}
const diff=git('diff','-U0');if(/\+\+ \[|List\.member/.test(diff))fail('BigO prohibited diff');const kernel=fs.readFileSync(path.join(root,'src/Elm/Kernel/SchelmRuntime.js'),'utf8');for(const fact of ['TextDecoder','randomBytes','setRawMode(false)','process.on(\'exit\'','process.off'])if(!kernel.includes(fact))fail(`missing kernel boundary ${fact}`);
for(const required of ['tests/oracle/import-gate.cjs','tests/pty/terminal.test.cjs','build/provenance.json','tests/mutation-gate.cjs','tests/replay.cjs'])if(!fs.existsSync(path.join(root,required)))fail(`audit evidence missing: ${required}`);
const provenance=JSON.parse(fs.readFileSync(path.join(root,'build/provenance.json'),'utf8'));try{cp.execFileSync('git',['merge-base','--is-ancestor',provenance.commit,'HEAD'],{cwd:root});}catch{fail('provenance commit is not an ancestor')}if(git('rev-parse',`${provenance.commit}^{tree}`)!==provenance.tree)fail('provenance tree mismatch');if(provenance.dirty)fail('provenance generated dirty');if(provenance.compilerBinarySha256!=='69987adf7062562b6e6dfd60b6709be3a06feeb90b096b9c84f673f2b97d8654')fail('compiler provenance mismatch');if(provenance.nodeBinarySha256!=='82e1a4da51b1870fc16495482f47c9bbb634dd02559f80ab5385090123cb034a')fail('node provenance mismatch');if(provenance.artifacts.debug!==artifactHashes.debug||provenance.artifacts.optimize!==artifactHashes.optimize)fail('generated artifact drift');if(provenance.artifacts.boundaryDebug!==sha(path.join(root,'build/boundary-debug.js'))||provenance.artifacts.boundaryOptimize!==sha(path.join(root,'build/boundary-optimize.js')))fail('compiled boundary artifact drift');for(const f of fs.readdirSync(path.join(root,'tests/replays'))){const x=JSON.parse(fs.readFileSync(path.join(root,'tests/replays',f)));if(provenance.traceDigests[x.subsystem]!==x.digest)fail(`trace digest drift ${x.subsystem}`);}
if(status)fail(`audit requires clean worktree, got ${status.split('\n').length} change(s)`);console.log(`audit source files=${exposed.length} provenance=${provenance.commit}`);console.log('PACKAGE SELF-AUDIT PASS; INDEPENDENT AUDIT AND HARNESS INTEGRATION REMAIN BLOCKED');
