'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');const fail=m=>{throw new Error(m)};const git=(...a)=>cp.execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim();const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const status=git('status','--porcelain');const exposed=JSON.parse(fs.readFileSync(path.join(root,'elm.json'),'utf8'))['exposed-modules'];if(exposed.length!==7)fail('public API drift');
const packageJson=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));if(packageJson.scripts.test!=='node scripts/canonical-test.cjs')fail('canonical npm test path drift');const artifactHashes={};for(const mode of ['debug','optimize']){const p=path.join(root,'build',`runtime-${mode}.js`);if(!fs.existsSync(p))fail(`missing ${mode}`);const s=fs.readFileSync(p,'utf8');if(/@fixture|FixtureObserver|process\.exit\s*\(/.test(s))fail(`artifact leak ${mode}`);artifactHashes[mode]=sha(p);console.log(`${mode} ${fs.statSync(p).size} ${artifactHashes[mode]}`);}
const diff=git('diff','-U0');if(/\+\+ \[|List\.member/.test(diff))fail('BigO prohibited diff');const kernel=fs.readFileSync(path.join(root,'src/Elm/Kernel/SchelmRuntime.js'),'utf8');for(const fact of ['TextDecoder','randomBytes','setRawMode(false)',"process.on('exit'",'process.off'])if(!kernel.includes(fact))fail(`missing kernel boundary ${fact}`);
for(const required of ['tests/oracle/import-gate.cjs','tests/pty/terminal.test.cjs','build/provenance.json','tests/mutation-gate.cjs','tests/replay.cjs','tests/compiled-replay.cjs','scripts/diagnose-package.cjs'])if(!fs.existsSync(path.join(root,required)))fail(`audit evidence missing: ${required}`);
const provenance=JSON.parse(fs.readFileSync(path.join(root,'build/provenance.json'),'utf8'));if(provenance.schema!=='schelm-node-runtime-provenance-v3')fail('provenance schema drift');if(!provenance.traceCounts||provenance.traceCounts.generatedPerSubsystem!==200||provenance.traceCounts.compiledZeroByteWritesPerMode!==257||provenance.traceCounts.compiledReplaySubsystems!==4)fail('provenance trace counts missing');if(!provenance.pty||provenance.pty.compiledArtifacts.length!==2||!provenance.pty.operations.includes('sharing'))fail('provenance PTY facts missing');if(!Array.isArray(provenance.commands)||provenance.commands.length<9)fail('provenance commands missing');
if(git('rev-parse','HEAD^')!==provenance.implementationCommit)fail('evidence commit must directly follow tested implementation');if(git('rev-parse',`${provenance.implementationCommit}^{tree}`)!==provenance.tree)fail('provenance tree mismatch');const sourceFiles=cp.execFileSync('find',['src','tests','scripts','fixture-apps','-type','f'],{cwd:root,encoding:'utf8'}).trim().split('\n').sort();const sourceDigest=crypto.createHash('sha256');for(const f of sourceFiles){sourceDigest.update(f+'\0');sourceDigest.update(fs.readFileSync(path.join(root,f)));}if(sourceDigest.digest('hex')!==provenance.sourceDigest)fail('provenance source digest mismatch');if(provenance.dirty)fail('provenance generated dirty');
if(provenance.compilerBinarySha256!=='69987adf7062562b6e6dfd60b6709be3a06feeb90b096b9c84f673f2b97d8654')fail('compiler provenance mismatch');if(provenance.nodeBinarySha256!=='82e1a4da51b1870fc16495482f47c9bbb634dd02559f80ab5385090123cb034a')fail('node provenance mismatch');if(provenance.artifacts.debug!==artifactHashes.debug||provenance.artifacts.optimize!==artifactHashes.optimize)fail('generated artifact drift');if(provenance.artifacts.boundaryDebug!==sha(path.join(root,'build/boundary-debug.js'))||provenance.artifacts.boundaryOptimize!==sha(path.join(root,'build/boundary-optimize.js')))fail('compiled boundary artifact drift');for(const f of fs.readdirSync(path.join(root,'tests/replays'))){const x=JSON.parse(fs.readFileSync(path.join(root,'tests/replays',f)));if(provenance.traceDigests[x.subsystem]!==x.digest)fail(`trace digest drift ${x.subsystem}`);}
if(status)fail(`audit requires clean worktree, got ${status.split('\n').length} change(s)`);console.log(`audit source files=${exposed.length} implementation=${provenance.implementationCommit}`);console.log('PACKAGE SELF-AUDIT PASS; INDEPENDENT AUDIT AND HARNESS INTEGRATION REMAIN BLOCKED');
