'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),os=require('node:os');
const root=path.resolve(__dirname,'..');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const git=(...a)=>cp.execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim();
const replays={};for(const f of fs.readdirSync(path.join(root,'tests/replays')).sort()){const x=JSON.parse(fs.readFileSync(path.join(root,'tests/replays',f)));replays[x.subsystem]=x.digest;}
const sourceFiles=cp.execFileSync('find',['src','tests','scripts','fixture-apps','-type','f'],{cwd:root,encoding:'utf8'}).trim().split('\n').sort();
const sourceDigest=crypto.createHash('sha256');for(const f of sourceFiles){sourceDigest.update(f+'\0');sourceDigest.update(fs.readFileSync(path.join(root,f)));}
const commands=['elm-format --validate src fixture-apps/production/src api-feasibility/package/src api-feasibility/app/src','node api-feasibility/scripts/build.cjs','node scripts/build-fixtures.cjs','node scripts/diagnose-package.cjs','node --test --test-timeout=60000 tests/node/*.test.cjs tests/pty/*.test.cjs','node tests/oracle/import-gate.cjs','node tests/mutation-gate.cjs','node tests/replay.cjs tests/replays/{console,signal,input,ticker}.json','node tests/compiled-replay.cjs','node tests/audit.cjs'];
const compiledReplaySubsystems=['console','signal','input','ticker'];
const compiledReplayEvidence=JSON.parse(cp.execFileSync(process.execPath,['tests/compiled-replay.cjs'],{cwd:root,encoding:'utf8'}).trim().split('\n').at(-1));
const p={schema:'schelm-node-runtime-provenance-v5',implementationCommit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),dirty:git('status','--porcelain')!=='',compilerAuthorizationCommit:'76bbe44424106c96f915cb24cd7f50d69f5cee0e',compilerBinarySha256:sha('/home/s.dormehl/git/elm-compiler/.worktrees/schelm-kernel-author/result/bin/elm'),nodeVersion:process.version,nodeBinarySha256:sha(process.execPath),platform:`${process.platform}-${process.arch}`,kernel:os.release(),sourceDigest:sourceDigest.digest('hex'),artifacts:{debug:sha(path.join(root,'build/runtime-debug.js')),optimize:sha(path.join(root,'build/runtime-optimize.js')),boundaryDebug:sha(path.join(root,'build/boundary-debug.js')),boundaryOptimize:sha(path.join(root,'build/boundary-optimize.js')),apiDebug:sha(path.join(root,'build/api-feasibility-debug.js')),apiOptimize:sha(path.join(root,'build/api-feasibility-optimize.js'))},traceDigests:replays,compiledReplaySubsystems,compiledReplayEvidence,traceCounts:{compiledModes:compiledReplayEvidence.modes.length,compiledCasesPerSubsystem:Object.fromEntries(Object.entries(compiledReplayEvidence.subsystems).map(([name,result])=>[name,result.casesPerMode])),compiledZeroByteWritesPerMode:257,ptyCasesPerMode:11},pty:{runner:'python3+pty',platform:`${process.platform}-${process.arch}`,kernel:os.release(),compiledArtifacts:['debug','optimize'],operations:['release','exit-backstop','poison-recovery','sharing','input-replay','input-close-reopen-aba','subscriber-limit','resize-current','resize-released','resize-stale']},commands,nonClaim:'Compiled replay evidence is one deterministic case per subsystem per mode, not 200 generated traces. Console and signal ordering are exact but independent-oracle equality is not claimed. Evidence commit must directly follow implementationCommit; tree and source digest bind the tested implementation. Compiler and Node bit-reproducibility are not claimed.'};
fs.mkdirSync(path.join(root,'build'),{recursive:true});fs.writeFileSync(path.join(root,'build/provenance.json'),JSON.stringify(p,null,2)+'\n');console.log(JSON.stringify(p));
